# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/users/pract/desktop/filtrofir/project_2/project_2.tmp/firaxi_v8_0_project/FirAxi_v8_0_project.cache/wt [current_project]
set_property parent.project_path c:/users/pract/desktop/filtrofir/project_2/project_2.tmp/firaxi_v8_0_project/FirAxi_v8_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths c:/Users/Pract/Desktop/FiltroFir/ip_repo [current_project]
set_property ip_output_repo c:/users/pract/desktop/filtrofir/project_2/project_2.tmp/firaxi_v8_0_project/FirAxi_v8_0_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  c:/Users/Pract/Desktop/FiltroFir/ip_repo/FirAxi_8.0/hdl/FirAxi_v8_0_S00_AXI.vhd
  c:/Users/Pract/Desktop/FiltroFir/ip_repo/FirAxi_8.0/hdl/FirAxi_v8_0.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top FirAxi_v8_0 -part xc7z020clg400-1


write_checkpoint -force -noxdef FirAxi_v8_0.dcp

catch { report_utilization -file FirAxi_v8_0_utilization_synth.rpt -pb FirAxi_v8_0_utilization_synth.pb }
